### ISSUE TITLE
/etc/nginx/ssl is not available when required during fresh local provisioning

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-Web-Provisioner#264]
```
==> wsuwp-dev:   Name: /etc/nginx/nginx.conf - Function: file.managed - Result: Changed
==> wsuwp-dev: ----------
==> wsuwp-dev:           ID: nginx-self-signed
==> wsuwp-dev:     Function: cmd.run
==> wsuwp-dev:         Name: openssl req -subj '/CN=default.wp.wsu.edu/O=Washington State University/C=US' -new -newkey rsa:2048 -sha256 -days 365 -nodes -x509 -keyout default.wp.wsu.edu.key -out default.wp.wsu.edu.cer
==> wsuwp-dev:       Result: False
==> wsuwp-dev:      Comment: An exception occurred in this state: Traceback (most recent call last):
==> wsuwp-dev:                 File "/usr/lib/python2.6/site-packages/salt/state.py", line 1703, in call
==> wsuwp-dev:                   **cdata['kwargs'])
==> wsuwp-dev:                 File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1649, in wrapper
==> wsuwp-dev:                   return f(*args, **kwargs)
==> wsuwp-dev:                 File "/usr/lib/python2.6/site-packages/salt/states/cmd.py", line 820, in run
==> wsuwp-dev:                   cret = mod_run_check(cmd_kwargs, onlyif, unless, creates)
==> wsuwp-dev:                 File "/usr/lib/python2.6/site-packages/salt/states/cmd.py", line 347, in mod_run_check
==> wsuwp-dev:                   cmd = __salt__['cmd.retcode'](unless, ignore_retcode=True, python_shell=True, **cmd_kwargs)
==> wsuwp-dev:                 File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 1794, in retcode
==> wsuwp-dev:                   password=kwargs.get('password', None))
==> wsuwp-dev:                 File "/usr/lib/python2.6/site-packages/salt/modules/cmdmod.py", line 460, in _run
==> wsuwp-dev:                   .format(cwd)
==> wsuwp-dev:               CommandExecutionError: Specified cwd '/etc/nginx/ssl/' either not absolute or does not exist
==> wsuwp-dev:      Started: 13:32:51.240124
==> wsuwp-dev:     Duration: 3.322 ms
==> wsuwp-dev:      Changes:  
==> wsuwp-dev: ----------
==> wsuwp-dev:           ID: nginx-dhparam
==> wsuwp-dev:     Function: cmd.run
==> wsuwp-dev:         Name: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
==> wsuwp-dev:       Result: False
==> wsuwp-dev:      Comment: Command "openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048" run
==> wsuwp-dev:      Started: 13:32:51.244866
==> wsuwp-dev:     Duration: 906.743 ms
==> wsuwp-dev:      Changes:  
==> wsuwp-dev:               ----------
==> wsuwp-dev:               pid:
==> wsuwp-dev:                   12774
==> wsuwp-dev:               retcode:
==> wsuwp-dev:                   1
==> wsuwp-dev:               stderr:
==> wsuwp-dev:                   Generating DH parameters, 2048 bit long safe prime, generator 2
==> wsuwp-dev:                   This is going to take a long time
==> wsuwp-dev:                   ....................................+...............................................................++*++*
==> wsuwp-dev:                   /etc/nginx/ssl/dhparam.pem: No such file or directory
==> wsuwp-dev:               stdout:
==> wsuwp-dev:   Name: /etc/nginx/sites-enabled/ - Function: file.directory - Result: Changed
```

**Comment by jeremyfelt** [comment]
Fixed in #265
